# Generated by Django 5.2 on 2025-04-18 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParkingSpot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "spot_number",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Spot Number"
                    ),
                ),
                (
                    "is_occupied",
                    models.BooleanField(default=False, verbose_name="Occupied"),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created on"),
                ),
                (
                    "updated_on",
                    models.DateTimeField(auto_now=True, verbose_name="Updated on"),
                ),
            ],
            options={
                "verbose_name": "Parking Spot",
                "verbose_name_plural": "Parking Spots",
            },
        ),
        migrations.CreateModel(
            name="ParkingRecords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Entry Time"),
                ),
                (
                    "exit_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Exit Time"
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created on"),
                ),
                (
                    "updated_on",
                    models.DateTimeField(auto_now=True, verbose_name="Updated on"),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parking_reords",
                        to="vehicles.vehicle",
                        verbose_name="Vehicle",
                    ),
                ),
                (
                    "parking_spot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parking_reords",
                        to="parking.parkingspot",
                        verbose_name="Vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Record",
                "verbose_name_plural": "Records",
            },
        ),
    ]
