# Generated by Django 5.2 on 2025-05-20 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingrecords",
            name="parking_spot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="parking_reords",
                to="parking.parkingspot",
                verbose_name="Parking Spot",
            ),
        ),
    ]
