# Generated by Django 5.2 on 2025-04-18 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Brand",
                "verbose_name_plural": "Brands",
            },
        ),
        migrations.CreateModel(
            name="VehicleType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Vehicle Type"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Vehicle Type",
                "verbose_name_plural": "Vehicle Types",
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "license_plate",
                    models.CharField(
                        max_length=12, unique=True, verbose_name="License Plate"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Car Model"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Black", "Black"),
                            ("Blue", "Blue"),
                            ("Carbon", "Carbon"),
                            ("Grafite", "Grafite"),
                            ("Gray", "Gray"),
                            ("Green", "Green"),
                            ("Lime", "Lime"),
                            ("Maroon", "Maroon"),
                            ("Orange", "Orange"),
                            ("Pearl", "Pearl"),
                            ("Purple", "Purple"),
                            ("Red", "Red"),
                            ("Silver", "Silver"),
                            ("White", "White"),
                            ("Yellow", "Yellow"),
                        ],
                        max_length=30,
                        null=True,
                        unique=True,
                        verbose_name="Car Color",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created on"),
                ),
                (
                    "updated_on",
                    models.DateTimeField(auto_now=True, verbose_name="Updated on"),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vehicles.brand",
                        verbose_name="Car Make",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicles",
                        to="customers.customer",
                        verbose_name="Car Owner",
                    ),
                ),
                (
                    "vehicle_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicles",
                        to="vehicles.vehicletype",
                        verbose_name="Vehicle Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle",
                "verbose_name_plural": "Vehicles",
            },
        ),
    ]
