# Generated by Django 5.2 on 2025-05-20 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Black", "Black"),
                    ("Blue", "Blue"),
                    ("Carbon", "Carbon"),
                    ("Grafite", "Grafite"),
                    ("Gray", "Gray"),
                    ("Green", "Green"),
                    ("Lime", "Lime"),
                    ("Maroon", "Maroon"),
                    ("Orange", "Orange"),
                    ("Pearl", "Pearl"),
                    ("Purple", "Purple"),
                    ("Red", "Red"),
                    ("Silver", "Silver"),
                    ("White", "White"),
                    ("Yellow", "Yellow"),
                ],
                max_length=30,
                null=True,
                verbose_name="Car Color",
            ),
        ),
    ]
